# Generated by Django 3.1.5 on 2021-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('cnumber', models.IntegerField(max_length=16)),
                ('cname', models.CharField(max_length=30)),
                ('cdate', models.IntegerField(max_length=2)),
                ('cyear', models.IntegerField(max_length=4)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
