# Generated by Django 3.1.5 on 2021-04-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnumber', models.IntegerField(max_length=16)),
                ('dname', models.CharField(max_length=30)),
                ('ddate', models.IntegerField(max_length=2)),
                ('dyear', models.IntegerField(max_length=4)),
                ('debit_cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
